# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

version = 1

[[annotations]]
path = [
    "*.md",
    "**/*.md",
    "*.html",
    "**/*.html",
    "**/*.scss"
]
SPDX-FileCopyrightText = '2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'CC-BY-SA-4.0+'

[[annotations]]
path = "CNAME"
SPDX-FileCopyrightText = '1900 Non-intellectual property work <https://creativecommons.org/publicdomain/zero/1.0/deed.zh-hant>'
SPDX-License-Identifier = 'CC0-1.0'

[[annotations]]
path = [
    "Gemfile.lock"
]
SPDX-FileCopyrightText = "1970 Computer-generated data, no copyright"
SPDX-License-Identifier = "CC0-1.0"
